services:
  - type: web
    name: picklestack
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: cd server && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
